"""Agregar campo activo a estudiantes

Revision ID: 201549d1f23c
Revises: 7af863d610df
Create Date: 2025-04-25 01:02:14.688069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '201549d1f23c'
down_revision: Union[str, None] = '7af863d610df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiantes', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudiantes', 'activo')
    # ### end Alembic commands ###
