"""create estudiantes table

Revision ID: 7af863d610df
Revises: 
Create Date: 2025-04-23 21:48:34.293554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af863d610df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiantes',
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.CHAR(length=10), nullable=False),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=True),
    sa.Column('correoInstitucional', sa.String(length=50), nullable=False),
    sa.Column('contrasenia', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('idEstudiante')
    )
    op.create_index(op.f('ix_estudiantes_correoInstitucional'), 'estudiantes', ['correoInstitucional'], unique=True)
    op.create_index(op.f('ix_estudiantes_idEstudiante'), 'estudiantes', ['idEstudiante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estudiantes_idEstudiante'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_correoInstitucional'), table_name='estudiantes')
    op.drop_table('estudiantes')
    # ### end Alembic commands ###
