"""agregar campos extra al estudiante

Revision ID: 91aee71e7e13
Revises: 0a4366afdf3a
Create Date: 2025-05-22 11:57:19.483344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91aee71e7e13'
down_revision: Union[str, None] = '0a4366afdf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudiantes', sa.Column('fotoPerfil', sa.String(length=255), nullable=True))
    op.add_column('estudiantes', sa.Column('numeroCelular', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudiantes', 'numeroCelular')
    op.drop_column('estudiantes', 'fotoPerfil')
    # ### end Alembic commands ###
