"""Aumentar longitud de campos de estudiante

Revision ID: 92c74682ba27
Revises: 
Create Date: 2025-06-10 14:06:15.673124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92c74682ba27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudiantes',
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
   # sa.Column('rol', sa.Enum('estudiante', 'administrador', name='rolenum'), nullable=False),
    sa.Column('fechaRegistro', sa.DateTime(), nullable=True),
    sa.Column('fotoPerfil', sa.String(length=255), nullable=True),
    sa.Column('numeroCelular', sa.String(length=100), nullable=True),
    sa.Column('correoInstitucional', sa.String(length=255), nullable=False),
    sa.Column('contrasenia', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idEstudiante')
    )
    op.create_index(op.f('ix_estudiantes_correoInstitucional'), 'estudiantes', ['correoInstitucional'], unique=True)
    op.create_index(op.f('ix_estudiantes_idEstudiante'), 'estudiantes', ['idEstudiante'], unique=False)
    op.drop_index('ix_intercambios_idIntercambio', table_name='intercambios')
    op.drop_table('intercambios')
    op.drop_table('cambios_correo_pendiente')
    op.create_foreign_key(None, 'libros', 'estudiantes', ['idEstudiante'], ['idEstudiante'], ondelete='CASCADE')
    op.create_foreign_key(None, 'solicitudes', 'estudiantes', ['estudiantePropietario'], ['idEstudiante'])
    op.create_foreign_key(None, 'solicitudes', 'estudiantes', ['estudianteSolicitante'], ['idEstudiante'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitudes', type_='foreignkey')
    op.drop_constraint(None, 'solicitudes', type_='foreignkey')
    op.drop_constraint(None, 'libros', type_='foreignkey')
    op.create_table('cambios_correo_pendiente',
    sa.Column('idCambio', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('idEstudiante', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nuevoCorreo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fechaSolicitud', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expiraEn', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('usado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idCambio', name='cambios_correo_pendiente_pkey')
    )
    op.create_table('intercambios',
    sa.Column('idIntercambio', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idSolicitud', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idEstudiante', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idEstudianteReceptor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idLibroOfrecido', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idLibroSolicitado', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fechaEncuentro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fechaCambioEstado', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('horaEncuentro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lugarEncuentro', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estado', postgresql.ENUM('en_proceso', 'finalizado', 'cancelado', name='estadointercambioenum'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idLibroOfrecido'], ['libros.idLibro'], name='intercambios_idLibroOfrecido_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idLibroSolicitado'], ['libros.idLibro'], name='intercambios_idLibroSolicitado_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idSolicitud'], ['solicitudes.idSolicitud'], name='intercambios_idSolicitud_fkey'),
    sa.PrimaryKeyConstraint('idIntercambio', name='intercambios_pkey')
    )
    op.create_index('ix_intercambios_idIntercambio', 'intercambios', ['idIntercambio'], unique=False)
    op.drop_index(op.f('ix_estudiantes_idEstudiante'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_correoInstitucional'), table_name='estudiantes')
    op.drop_table('estudiantes')
    # ### end Alembic commands ###
