"""empty message

Revision ID: e3b408371494
Revises: 3c80159f29ae
Create Date: 2025-04-30 16:19:55.308567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b408371494'
down_revision: Union[str, None] = '3c80159f29ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idCategoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_idCategoria'), 'categorias', ['idCategoria'], unique=False)
    op.create_table('libros',
    sa.Column('idLibro', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('disponible', 'intercambio', name='estadolibroenum'), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('visibleCatalogo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['categorias.idCategoria'], ),
    sa.ForeignKeyConstraint(['idEstudiante'], ['estudiantes.idEstudiante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idLibro')
    )
    op.create_index(op.f('ix_libros_idLibro'), 'libros', ['idLibro'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_libros_idLibro'), table_name='libros')
    op.drop_table('libros')
    op.drop_index(op.f('ix_categorias_idCategoria'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
