"""empty message

Revision ID: f277356d0965
Revises: 1b50e01f4dff
Create Date: 2025-04-30 16:59:14.326540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f277356d0965'
down_revision: Union[str, None] = '1b50e01f4dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects.postgresql import ENUM

# Define el tipo ENUM
estado_libro_enum = ENUM('disponible', 'intercambio', name='estadolibroenum', create_type=False)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    estado_libro_enum.create(op.get_bind(), checkfirst=True)  # Evita duplicar el tipo ENUM
    op.create_table('categorias',
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idCategoria'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_idCategoria'), 'categorias', ['idCategoria'], unique=False)
    op.create_table('libros',
    sa.Column('idLibro', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', estado_libro_enum, nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('idEstudiante', sa.Integer(), nullable=False),
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('visibleCatalogo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['categorias.idCategoria'], ),
    sa.ForeignKeyConstraint(['idEstudiante'], ['estudiantes.idEstudiante'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idLibro')
    )
    op.create_index(op.f('ix_libros_idLibro'), 'libros', ['idLibro'], unique=False)
    op.create_table('solicitudes',
    sa.Column('idSolicitud', sa.Integer(), nullable=False),
    sa.Column('estudianteSolicitante', sa.Integer(), nullable=True),
    sa.Column('estudiantePropietario', sa.Integer(), nullable=True),
    sa.Column('libroOfrecido', sa.Integer(), nullable=True),
    sa.Column('libroSolicitado', sa.Integer(), nullable=True),
    sa.Column('fechaSolicitud', sa.DateTime(), nullable=True),
    sa.Column('fechaEncuentro', sa.DateTime(), nullable=True),
    sa.Column('horaEncuentro', sa.DateTime(), nullable=True),
    sa.Column('lugarEncuentro', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aceptada', 'rechazada', name='estadosolicitudenum'), nullable=True),
    sa.ForeignKeyConstraint(['estudiantePropietario'], ['estudiantes.idEstudiante'], ),
    sa.ForeignKeyConstraint(['estudianteSolicitante'], ['estudiantes.idEstudiante'], ),
    sa.ForeignKeyConstraint(['libroOfrecido'], ['libros.idLibro'], ),
    sa.ForeignKeyConstraint(['libroSolicitado'], ['libros.idLibro'], ),
    sa.PrimaryKeyConstraint('idSolicitud')
    )
    op.create_index(op.f('ix_solicitudes_idSolicitud'), 'solicitudes', ['idSolicitud'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_idSolicitud'), table_name='solicitudes')
    op.drop_table('solicitudes')
    op.drop_index(op.f('ix_libros_idLibro'), table_name='libros')
    op.drop_table('libros')
    op.drop_index(op.f('ix_categorias_idCategoria'), table_name='categorias')
    op.drop_table('categorias')
    estado_libro_enum.drop(op.get_bind(), checkfirst=True)  # Elimina el tipo ENUM si existe
    # ### end Alembic commands ###
